version: '3.8'

services:

  web:
    build: ./todo
    container_name: application
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file: .env.todoapp
    restart: always

  db:
    image: postgres:12.0-alpine
    container_name: data
    volumes:
      - ./dbdata/:/var/lib/postgresql/data/
    env_file: .env.todoapp

