# Generated by Django 3.0.8 on 2020-08-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20200729_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
    ]
