# Generated by Django 3.0.8 on 2020-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20200804_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
